### PR TITLE
Add ruamel.yaml as a dependency

### PR DESCRIPTION
**Pull request by brachbach**
Used in https://github.com/oughtinc/ice-ought-shared/pull/2

### CODE REVIEW

**Comment by lslunis** [comment]
How large is the docker image after this change?

**Comment by lslunis** [comment]
This is a very large `poetry.lock` diff, did you run `poetry add`? That unavoidably upgrades everything in the lockfile to the max permissible version.

**Comment by lslunis** [comment]
By the way, if this is ready to go in I'd be happy to take over this PR.

**Comment by brachbach** [comment]
@lslunis it's possible that I accidentally ran `poetry add`

on further thought, let's close this PR and make a new PR based on `main`, rather than on Justin's branch

if you want to take that over, that's great -- TBC the only thing to do is to successfully and correctly install `"ruamel.yaml" = "^0.17.21"`

LMK whether you want to take it!

**Comment by brachbach** [comment]
(and TBC, yes, this is ready to go in, we do in fact want this dependency)

**Comment by lslunis** [comment]
Okay, I'll send you a PR shortly!

**Pull request closed without merging**
