### PR TITLE
Don't download punkt at import time

### PR DESCRIPTION
**Pull request by lslunis**
Supersedes #228

### CODE REVIEW

**Review by alexmojaki — APPROVED** [review]

**Comment by alexmojaki** [comment]
Now I'm getting this every time:

```
[nltk_data] Downloading package punkt to /home/alex/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
```

**Comment by amosjyng** [comment]
Thanks, this does take care of not downloading punkt until it's needed! But I don't think function memoization persists across runs, which should be why you're seeing that every time. Setting a global variable and updating it after download doesn't help because the initial attempted download that generates those logs will still happen every time.

Instead, the check for whether punkt is already downloaded should happen before the call to `nltk.download`, which is how I came across [this answer](https://stackoverflow.com/a/40402752). According to that answer, it seems like the recommended way is simply to check if you get a `LookupError` or not, which is why I took that approach in the original PR.

Ideally this would be fixed in NLTK itself, so perhaps I should open a PR there

**Comment by alexmojaki** [comment]
Ah, neither of us realised your design was about nicely balancing loud vs quiet logging.

Here's how I suggest using your idea:

```python
@cache
def download_punkt():
    try:
        # use punkt
    except LookupError:
        nltk.download("punkt", quiet=False)
```

**Comment by amosjyng** [comment]
Ahh yeah that sounds good! LMK if you'd like me to open a PR for that. I was mostly concerned about the download, but I certainly don't want you to be annoyed by superfluous console output either :)

**Comment by alexmojaki** [comment]
Yes please for a PR :)

**Comment by amosjyng** [comment]
Ok done at #244 !

**Pull request merged**
