### PR TITLE
Recipes for summarize, multiquestion, rephrase

### PR DESCRIPTION
**Pull request by nathanneuro**
You may not want all these recipies, and even if you do, they need to be cleaned up a bit to be up to the standard of your
 other code, but I wanted to contribute the ideas I came up with while listening to your talk. Hope you like some of them!'

### CODE REVIEW

**Comment by lslunis** [comment]
Thanks, I'll take a look at this as soon as I'm done preparing the next ICE release!

**Review by alexmojaki — COMMENTED** [review]
Hello :wave: Please don't take this 'review' too seriously. I'm not an Ought employee, and I understand you said these are ideas in need of cleanup, I'm just interested in the conversation.

I think it's important to note that recipes like `AnswerNTimes` don't seem to fit the philosophies of 'factored cognition' and 'supervise process over outcome' well. For example, you could set a high temperature and set `attempts` to a million and that might work quite well (it worked for AlphaCode :shrug:) but a human can't really supervise/debug the process. The recipes can still be very useful, especially for evaluation, but maybe a disclaimer or something is needed.

I also think it'd be good for `AnswerNTimes` to accept a generic callable parameter like `answerer = lambda: AmplifiedQA().run(question, depth)` rather than being tied to a specific recipe. Similarly `AnswerUntilBest` could be a more generic 'parameter optimiser' with parameters like `answerer = lambda depth: AnswerNTimes().run(question, depth, ...)` and `params = range(1, 4)` where `params` is any iterable of parameters that get successively passed to `answerer`. I haven't looked closely, but the other Rephrase/Summarize recipes look like they might fit nicely into such a generalisation, although you'd also need a generic parameter for the ranking.

**Review by lslunis — CHANGES_REQUESTED** [review]
I'd like to get some or all of these recipes merged once @alexmojaki's comments are addressed.

@stuhlmueller Any thoughts?

Caveat: I'm about to **rewrite git history** to make the repo smaller (and then obviously never do that again, because it's terrible). That might cause problems with eventually merging this PR, and I can help with that when the time comes.

**Comment by lslunis** [comment]
Looks like when I force-pushed main, it caused this PR to close(!). I'm going to reopen it tomorrow or Sunday based on the new main.

**Comment by lslunis** [comment]
Sorry, I forgot to put this on my todo list and it didn't happen. Opening a new version of this PR is now next on my todo list after getting ICE officially released.

**Pull request closed without merging**
